### ISSUE TITLE
Error when compiling sass/scss

### ISSUE THREAD

**Issue by eduardhojbota** [electronjs/electron-compile#14]
Now when compiling a valid scss/sass file, the following error is received:

```
Failed to compile D:/Projects/nepenthe-on-node/app/styles/main.scss: A dynamic link library (DLL) initialization routine failed.
d:\Projects\nepenthe-on-node\node_modules\electron-compile\node_modules\electron-compilers\node_modules\node-sass\vendor\win32-x64-44\binding.node
Error: A dynamic link library (DLL) initialization routine failed.
d:\Projects\nepenthe-on-node\node_modules\electron-compile\node_modules\electron-compilers\node_modules\node-sass\vendor\win32-x64-44\binding.node
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
  at Module.load (module.js:351:32)
  at Function.Module._load (module.js:306:12)
  at Module.require (module.js:361:17)
  at require (module.js:380:17)
  at Object.<anonymous> (d:\Projects\nepenthe-on-node\node_modules\electron-compile\node_modules\electron-compilers\node_modules\node-sass\lib\index.js:16:15)
  at Module._compile (module.js:426:26)
  at BabelCompiler.loadFile (d:\Projects\nepenthe-on-node\node_modules\electron-compile\node_modules\electron-compile-cache\lib\compile-cache.js:199:23)
  at Object.value [as .js] (d:\Projects\nepenthe-on-node\node_modules\electron-compile\node_modules\electron-compile-cache\lib\compile-cache.js:240:26)
  at Module.load (module.js:351:32)
  at Function.Module._load (module.js:306:12)
  at Module.require (module.js:361:17)
  at require (module.js:380:17)
  at ScssCompiler.initializeCompiler (d:\Projects\nepenthe-on-node\node_modules\electron-compile\node_modules\electron-compilers\lib\css\scss.js:91:14)
  at ScssCompiler.loadFile (d:\Projects\nepenthe-on-node\node_modules\electron-compile\node_modules\electron-compile-cache\lib\compile-cache.js:206:49)
  at Function.<anonymous> (d:\Projects\nepenthe-on-node\node_modules\electron-compile\lib\protocol-hook.js:134:33)
```

Platform: Windows 8.1 x64

P.S. It works on OSX 10.10 tho

**Comment by paulcbetts** [comment]
Ugh, this is a node-sass bug, you can try using https://github.com/electronjs/electron-rebuild - node-pre-gyp sucks with Electron right now

**Comment by eduardhojbota** [comment]
Unfortunately electron-rebuild did not help.

**Comment by eduardhojbota** [comment]
After further investigation, it the origin of these issues is actually node-sass.

**Comment by paulcbetts** [comment]
@eduardhojbota If there is a node-sass bug open, can you link it here?

**Comment by eduardhojbota** [comment]
There isn't one at the moment, so I will create one and post it here.

**Comment by paulcbetts** [comment]
@eduardhojbota Thanks!

**Comment by eduardhojbota** [comment]
Looks like we've got an answer pretty quickly. You might want to check it out.

**Comment by eduardhojbota** [comment]
Considering that node-sass does not offer support for electron (atom-shell) I shall reopen this issue.

**Comment by paulcbetts** [comment]
I have a plan to fix this, :soon:

**Comment by jgeurts** [comment]
Any word on a resolution for this issue?

**Comment by AnthonyPorthouse** [comment]
@jgeurts Running Electron v0.33.1 and electron-compile v0.9.2, this seems to work correctly for me now at least.

**Comment by eduardhojbota** [comment]
@AnthonyPorthouse, could you please specify your operating system too?

**Comment by JoyceBabu** [comment]
I am getting the same error, but with ZeroMQ (zmq). Running `electron-rebuild` worked for me.

**Comment by AnthonyPorthouse** [comment]
@eduardhojbota Linux x86-64, but I was having the same issue previously.

**Comment by paulcbetts** [comment]
Sass is removed from the newest version of electron-compile, sorry :(

**Comment by eduardhojbota** [comment]
But if the node-sass was working for Unix, why remove it entirely?

**Comment by paulcbetts** [comment]
@eduardhojbota In the latest version of node-sass, it breaks Linux too for _everyone_, even if you're not using node-sass, by including a module that uses `node-pre-gyp`

**Comment by Aldlevine** [comment]
So I stumbled upon this issue when trying to get node-sass to work in electron myself. I figured out a way to do it on my system (Debian Jessie). Using nvm I switched to the version of node that electron is using, currently 5.1.1, and installed node-sass. It worked flawlessly after that. Just figured that I'd share my solution.

**Comment by stefanKuijers** [comment]
@Aldlevine That's a great first step. For me it works as well on Xubuntu. When create my app on Xubuntu and run it on Xubuntu it works but it does not work if I want to distribute the app for Windows or OSX. 

Do you know how to solve this for other platforms as well? 
For me it looks like the only solution would be to have Windows, OSX and Lunix installed and build from a platform for that platform. :| 

What are your thoughts on that?

**Comment by stefanKuijers** [comment]
@paulcbetts so, if I understand right; the solution merged in with [this PR](https://github.com/mapbox/node-pre-gyp/pull/175) ````--runtime=electron```` is no longer valid?

**Comment by stefanKuijers** [comment]
@Aldlevine I've tried the same for windows but that did not solve the problem. :(
