### ISSUE TITLE
Failed to compile index.html

### ISSUE THREAD

**Issue by jgeurts** [electronjs/electron-compile#42]
I recently updated my app to latest electron and electron-compile. I'm now getting a message `Failed to compile C:/.../resources/app.asar/static/index.html` when my app starts up. That index file is the only html file that is loaded - everything else gets loaded from an x-include tag.

I've tried including the static directory in the electron-compile cache, I've tried to unpack the static directory from the asar file, and I've even tried removing all content from that file, with no changes in the error message. 

Am I missing something obvious to resolve this situation? Any help would be appreciated and if I can provide more info, please let me know.

**Comment by paulcbetts** [comment]
Usually when a file fails to compile it'll give you exception details, does it _just_ show that?

**Comment by jgeurts** [comment]
This is the stacktrace:

```
Failed to compile C:/Users/jgeurts/AppData/Local/MyApp/app-1.2.64/resources/app.asar/static/index.html: Asked to compile C:/Users/jgeurts/AppData/Local/MyApp/app-1.2.64/resources/app.asar/static/index.html in production!
Error: Asked to compile C:/Users/jgeurts/AppData/Local/MyApp/app-1.2.64/resources/app.asar/static/index.html in production!
    at ReadOnlyCompiler.compile (C:\Users\jgeurts\AppData\Local\MyApp\app-1.2.64\resources\app.asar\node_modules\electron-compile\lib\read-only-compiler.js:41:13)
    at ReadOnlyCompiler.loadFile (C:\Users\jgeurts\AppData\Local\MyApp\app-1.2.64\resources\app.asar\node_modules\electron-compile\node_modules\electron-compile-cache\lib\compile-cache.js:239:19)
    at Function.callee$1$0$ (C:\Users\jgeurts\AppData\Local\MyApp\app-1.2.64\resources\app.asar\node_modules\electron-compile\lib\protocol-hook-44.js:211:37)
    at tryCatch (C:\Users\jgeurts\AppData\Local\MyApp\app-1.2.64\resources\app.asar\node_modules\electron-compile\lib\regenerator.js:59:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\jgeurts\AppData\Local\MyApp\app-1.2.64\resources\app.asar\node_modules\electron-compile\lib\regenerator.js:307:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\jgeurts\AppData\Local\MyApp\app-1.2.64\resources\app.asar\node_modules\electron-compile\lib\regenerator.js:92:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\jgeurts\AppData\Local\MyApp\app-1.2.64\resources\app.asar\node_modules\electron-compile\lib\regenerator.js:128:37)
    at process._tickDomainCallback (node.js:412:9)
```

**Comment by paulcbetts** [comment]
Yep, so you're in production mode, but index.html isn't in the cache - you need to add index.html to your compile step

**Comment by jgeurts** [comment]
The weird thing is that I had added the static directory to the cache and still get that exception..

**Comment by paulcbetts** [comment]
Hm, if you're having trouble probably the easiest thing to do is to just ship the compilers and take the 10MB size hit

**Comment by jgeurts** [comment]
Sigh... Looks like the contents of that file were getting modified after the cache step, but before the installer was built. Organizing those steps a bit better has fixed things. Thanks for listening and helping, though!
