### ISSUE TITLE
Fails with App threw an error when running [Error: Electron compilers not found but were requested to be loaded]

### ISSUE THREAD

**Issue by gramster** [electronjs/electron-compile#53]
I have tried both the hard way and the easy way instructions with the same result.

    npm install --save-dev electron-prebuilt-compile

and:

    npm install --save electron-compile
    npm install --save-dev electron-compilers

Relevant part of my package.json (after simple way):

      "dependencies": {
        "codemirror": "^5.10.0"
      },
      "devDependencies": {
        "chai": "^3.4.1",
        "electron-mocha": "^0.7.0",
        "electron-packager": "^5.2.0",
        "electron-prebuilt-compile": "^0.36.1",
        "eslint": "^1.10.3",
        "eslint-plugin-babel": "^3.0.0"
     },

I've tried adding babel packages as explicit dependencies too.

My start file is compile.js:

    // Enable precompilation from ES6/Typescript/etc.
    require('electron-compile').init(__dirname, 'main.js');

But when I do 'npm start' I get the error in the title.

**Comment by gnestor** [comment]
Using Node 5 (5.2.0) to `npm install` and run solved this for me...

**Comment by gramster** [comment]
Thanks for that suggestion. Updating node has resulted in me getting a different error. My previous starting script was app.js. I now instead point to a compile.js script in the same top-level directory as app.js. compile.js is:

    require('electron-compile').init(__dirname, './app');

(I've tried 'app', 'app.js', as well).

I now get:

    Error: Cannot find module './app'

**Comment by gramster** [comment]
Debug output from above:

      electron-compile:config-parser Using package.json or default parameters at /Users/gram/app-new/app +0ms
      electron-compile:inline-html Setting up inline HTML compilers: [] +16ms
      electron-compile:config-parser Using default cache directory: /var/folders/00/17c28000h01000cxqpysvccm004xh9/T/compileCache_223d99ba6836902bb498c917ac697c21 +4ms
      electron-compile:config-parser Creating CompilerHost: {"appRoot":"/Users/gram/app-new/app","options":{"application/javascript":{"presets":["stage-0","es2015","react"],"sourceMaps":"inline"}},"rootCacheDir":null}, rootCacheDir = /var/folders/00/17c28000h01000cxqpysvccm004xh9/T/compileCache_223d99ba6836902bb498c917ac697c21 +0ms
      electron-compile:config-parser Setting options for application/javascript: {"presets":["stage-0","es2015","react"],"sourceMaps":"inline"} +1ms
      electron-compile:config-parser Created compiler host with options: {"appRoot":"/Users/gram/app-new/app","options":{"application/javascript":{"presets":["stage-0","es2015","react"],"sourceMaps":"inline"}},"rootCacheDir":null} +0ms
      electron-compile:compiler-host Compiling /Users/gram/app-new/app/compile.js +11ms
      electron-compile:file-change-cache Cache entry for /compile.js: {"ctime":1452189158000,"size":153,"info":{"hash":"b9a371bdee68900837254d2f144a971e8fda7ce8","isMinified":false,"isInNodeModules":false,"hasSourceMap":false,"isFileBinary":false}} +3ms
      electron-compile:compile-cache Fetching /Users/gram/app-new/app/compile.js from cache +1ms
      electron-compile:compile-cache Path for BabelCompiler: /var/folders/00/17c28000h01000cxqpysvccm004xh9/T/compileCache_223d99ba6836902bb498c917ac697c21/56efeefb842dce781276b40415354d265e9f86a6 +1ms
      electron-compile:compile-cache Set up with parameters: {"name":"BabelCompiler","version":"6.4.0","options":{"presets":["stage-0","es2015","react"],"sourceMaps":"inline"}} +0ms
      electron-compile:config-parser Using package.json or default parameters at /Users/gram/app-new/app +1ms
      electron-compile:inline-html Setting up inline HTML compilers: [] +0ms
      electron-compile:config-parser Using default cache directory: /var/folders/00/17c28000h01000cxqpysvccm004xh9/T/compileCache_223d99ba6836902bb498c917ac697c21 +1ms
      electron-compile:config-parser Creating CompilerHost: {"appRoot":"/Users/gram/app-new/app","options":{"application/javascript":{"presets":["stage-0","es2015","react"],"sourceMaps":"inline"}},"rootCacheDir":null}, rootCacheDir = /var/folders/00/17c28000h01000cxqpysvccm004xh9/T/compileCache_223d99ba6836902bb498c917ac697c21 +0ms
      electron-compile:config-parser Setting options for application/javascript: {"presets":["stage-0","es2015","react"],"sourceMaps":"inline"} +0ms
      electron-compile:config-parser Created compiler host with options: {"appRoot":"/Users/gram/app-new/app","options":{"application/javascript":{"presets":["stage-0","es2015","react"],"sourceMaps":"inline"}},"rootCacheDir":null} +0ms

**Comment by gramster** [comment]
And node log:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
    2 info using npm@3.3.12
    3 info using node@v5.4.0
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info lifecycle App@0.0.1~prestart: App@0.0.1
    6 silly lifecycle App@0.0.1~prestart: no script for prestart, continuing
    7 info lifecycle App@0.0.1~start: App@0.0.1
    8 verbose lifecycle App@0.0.1~start: unsafe-perm in lifecycle true
    9 verbose lifecycle App@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/gram/app-new/app/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/gram/anaconda/bin://anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/Users/gram/bin:/opt/local/bin:/Users/gram/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Users/gram/anaconda/bin://anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/gram/anaconda/bin:/Users/gram/anaconda/bin:/Users/gram/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/bin:/Users/gram/bin:/opt/local/bin:/Users/gram/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Applications/Utilities/pulse-dev/bin:/depot_tools:~/Downloads/apache-maven-3.2.5/bin:/Users/gram/gradle-2.3/bin:/depot_tools:~/Downloads/apache-maven-3.2.5/bin:/Users/gram/gradle-2.3/bin:/Users/gram/app-new/tools
    10 verbose lifecycle App@0.0.1~start: CWD: /Users/gram/app-new/app
    11 silly lifecycle App@0.0.1~start: Args: [ '-c', 'electron compile.js' ]
    12 silly lifecycle App@0.0.1~start: Returned: code: 1  signal: null
    13 info lifecycle App@0.0.1~start: Failed to exec start script
    14 verbose stack Error: App@0.0.1 start: `electron compile.js`
    14 verbose stack Exit status 1
    14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at EventEmitter.emit (events.js:172:7)
    14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at ChildProcess.emit (events.js:172:7)
    14 verbose stack     at maybeClose (internal/child_process.js:821:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    15 verbose pkgid App@0.0.1
    16 verbose cwd /Users/gram/app-new/app
    17 error Darwin 15.2.0
    18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
    19 error node v5.4.0
    20 error npm  v3.3.12
    21 error code ELIFECYCLE
    22 error App@0.0.1 start: `electron compile.js`
    22 error Exit status 1
    23 error Failed at the App@0.0.1 start script 'electron compile.js'.

**Comment by paulcbetts** [comment]
> Error: Cannot find module './app'

I think that the tricks we used to make this relative path work are busted. For now, just set up an absolute path or use `require.resolve` to find it

**Comment by gramster** [comment]
Thanks - early tests look like absolute path is working

**Comment by aendrew** [comment]
I've just fought this for five minutes. The documentation should really be updated...
